---
driver:
  require_chef_omnibus: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver:
      name: docker
      use_sudo: false
      socket: tcp://192.168.59.103:2375
      image: ubuntu:12.04
    attributes: { "ad-buildtools": { "developers": [ "ubuntu" ] } }

suites:
  - name: default
    run_list:
      - recipe[ad-buildtools]
